### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by snekiam**
I think this will fix the deploy issue - the last successful deploy was on bionic, the first unsuccessful was on focal.  My hunch is that ubuntu:latest switched from bionic to focal causing the failure

## What's New?
This should fix the deploy issue.

### CODE REVIEW

**Comment by snekiam** [comment]
> My hunch is that ubuntu:latest switched from bionic to focal causing the failure

I should clarify that my hunch is backed up by the logs.

**Review by chidiewenike — APPROVED** [review]

**Review by Jason-Ku — APPROVED** [review]
glad to support a hunch. let the ship sail

**Comment by mfekadu** [comment]
Cool! Was the hunch correct @snekiam ?

**Comment by snekiam** [comment]
Well now there's a different error.  So that's a start I suppose.

**Pull request merged**
