### PR TITLE
REST hooks for validator app to update and delete QAPairs

### PR DESCRIPTION
**Pull request by Waidhoferj**
## What's New?
The web team is building a Nimbus validator to ensure high quality QAPairs. We need 2 api endpoints to make the app work:
- update: fix aspects of a QAPair during validation.
- delete: erase a QA Pair that is beyond saving.

In the process of making these two endpoints, I made the following additional changes:
- added a general purpose ``delete_entity`` function.
- modified the ``update_entity`` function to work with the ``Entity`` interface #174.
- modified ``QuestionAnswerPair`` class to inherit from ``Entity``.
- added validation, formatting and updating functionality to ``QuestionAnswerPair``.
## Type of change (pick-one)
- [ ] Bug fix (_non-breaking change which fixes an issue_)
- [x] New feature (_non-breaking change which adds functionality_)
- [ ] Breaking change (_fix or feature that would cause existing functionality to not work as expected_)
- [ ] This change requires a documentation update

## How Has This Been Tested?
I checked updating all fields and deleting the test row with Postman.
The following requests can be found in the `CSAI Web` team folder:
- **UpdateQAPair** with endpoint ``new_data/update_phrase``.
- **DeleteQAPair** with endpoint ``new_data/delete_phrase``.

**I won't be able to make changes after June 14, so I leave it up to you all to carry this through.**
You can still reach out to me with general questions.

### CODE REVIEW

**Review by snekiam — APPROVED** [review]
Didn't look too deeply, but looks good to me!

**Review by Jason-Ku — APPROVED** [review]
looks good!

**Review by thegooman — APPROVED** [review]
LGTM

**Review by masonmcelvain — APPROVED** [review]
Great legwork, thanks for getting the ball rolling! Excited to take this on over the summer.

**Pull request merged**
