### PR TITLE
added the OfficeHours entity schema

### LINKED ISSUE #116: Create NimbusDatabase Entity for OfficeHour data
## Objective
Enhance the NimbusDatabase’s ability to answer questions like

```python
"What is Dr. John Smith's office hours for this quarter?"
```

Or even 

```python
"When is Dr. John Smith available this quarter?"
```

The Computer Science department office will provide us with an excel file containing the latest office hours for each professor upon email as early as the 2nd week of each academic quarter. 

## Key Result
- [x] create an Entity schema for `OfficeHour`
- [x] make sure that the `save_entity` function properly saves a new `OfficeHour`
- [ ] create a `flask_api` endpoint to `save_office_hours`

#### what the data looks like

7FE0FD97-60F7-443E-9C1E-5FB79824424D

#### good points of contact
* @chidiewenike - for how the data is sourced
* @cameron-toy - for how the data is scraped
* @austinsilveria - for how the data is scraped
* @mfekadu - for any other questions

### PR DESCRIPTION
**Pull request by chidiewenike**
## What's New?

Added the "OfficeHours" entity class to accommodate for answering questions about office hours. The format is comparable to the other entities.

## Type of change (pick-one)
- [ ] Bug fix (_non-breaking change which fixes an issue_)
- [x] New feature (_non-breaking change which adds functionality_)
- [ ] Breaking change (_fix or feature that would cause existing functionality to not work as expected_)
- [ ] This change requires a documentation update

## How Has This Been Tested?

GitHub Logo

The entity was tested by extracting information from the database and displaying it to the screen. The image above shows the instructions on how it was completed and it was run on Windows 10.

## Checklist (check-all-before-merge)
_formatting help: `- [x]` means "checked' and `- [ ]` means "unchecked"_

- [ ] I documented my code according to the [Google Python Style Guide][1]

- [ ] I ran `./build_docs.sh` and the docs look fine

- [ ] I ran `./type_check.sh` and got no errors

- [ ] I ran `./format.sh` because it automatically cleans my code for me 😄 

- [ ] I ran `./lint.sh` to check for what "format" missed

- [ ] I added my tests to the `/tests` directory

- [ ] I ran `./run_tests.sh` and all the tests pass

[1]: https://google.github.io/styleguide/pyguide.html

### CODE REVIEW

**Comment by mfekadu** [comment]
@chidiewenike 

I think you've added more code, right? 

Have you done a `git push` recently?

**Review by snekiam — APPROVED** [review]

**Comment by chidiewenike** [comment]
@mfekadu The save_office_hours is written but I need to ensure it is intuitively complete.

**Comment by chidiewenike** [comment]
@mfekadu Added the save_office_hours function to flask_api.py and created office_hours_post_request.py to send the post request.

**Review by Jason-Ku — APPROVED** [review]
Thanks for rebasing, everything looks perfect.

**Pull request merged**
