### PR TITLE
Create google.yml

### PR DESCRIPTION
**Pull request by snekiam**
This still needs some configured secrets to actually work.

### CODE REVIEW

**Comment by mfekadu** [comment]
So #36 is related to this right? Should we wait until #36 is merged or go ahead and merge this?

**Comment by snekiam** [comment]
Yes, that's probably true - this won't explicitly *not* work without #36 - #36 just puts some placeholder files in and adds some stuff to the .gitignore to make sure keys don't get pushed accidentally.

**Comment by snekiam** [comment]
I've updated this PR with some more files required for google cloud deployes - @mfekadu can you take another look?

**Comment by mfekadu** [comment]
@snekiam I'm unable to verify the `google.yml` without 

1. merging into the `dev` branch (because GitHub runs the workflow on a push to `dev`) (also see the "P.S." below)
2. including the secrets referenced inside `google.yml`

```
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
```

**So let's add those secrets together on Sunday (or you can [feel free to add the secrets here](http://github.com/calpoly-csai/api/settings/secrets))**

P.S. An alternative way to test the `google.yml` workflow is my creating a dummy repository on GitHub. If you have time, would you like to try that and include screenshots of how that went here?

**Comment by snekiam** [comment]
Its probably best if I just create a dummy repo for testing - I haven't really been able to test this yet.

**Comment by mfekadu** [comment]
related #67

**Pull request closed without merging**
