### PR TITLE
Handle OperationalError by doing a db.session.rollback

### LINKED ISSUE #167: /ask/  sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
# Stacktrace

<details><summary>expand to see</summary>
<p>

```
[2020-05-28 16:53:21,075] ERROR in app: Exception on /ask [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1171, in _execute_context
    conn = self._revalidate_connection()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 456, in _revalidate_connection
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Can't reconnect until invalid transaction is rolled back

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/nimbus/flask_api.py", line 122, in handle_question
    response = {"answer": nimbus.answer_question(question)}
  File "/nimbus/nimbus.py", line 42, in answer_question
    answer = qa.answer(ans_dict)
  File "/nimbus/QA.py", line 52, in answer
    db_data = self.db_query(extracted_vars, self.db)
  File "/nimbus/QA.py", line 231, in _chain_db_access
    for key, val in fn(extracted_vars, db).items():
  File "/nimbus/QA.py", line 95, in _get_property
    value = db.get_property_from_entity(
  File "/nimbus/database_wrapper.py", line 583, in get_property_from_entity
    props = self._get_property_from_entity(prop, entity, identifier, tag_column_map)
  File "/nimbus/database_wrapper.py", line 558, in _get_property_from_entity
    for row in query_obj.all():
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3233, in all
    return list(self)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3389, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3414, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1175, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1171, in _execute_context
    conn = self._revalidate_connection()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 456, in _revalidate_connection
    raise exc.InvalidRequestError(
sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
[SQL: SELECT `Profs`.first_name AS `Profs_first_name`, `Profs`.last_name AS `Profs_last_name`, `Profs`.phone_number AS `Profs_phone_number`, `Profs`.research_interests AS `Profs_research_interests`, `Profs`.email AS `Profs_email`, `Profs`.office_hours AS `Profs_office_hours`, `Profs`.platform AS `Profs_platform`, `Profs`.latest_quarter AS `Profs_latest_quarter`, `Profs`.office AS `Profs_office`, `Profs`.department AS `Profs_department`, `Profs`.title AS `Profs_title`
FROM `Profs`]
[parameters: [immutabledict({})]]
```

</p>
</details>

### PR DESCRIPTION
**Pull request by snekiam**
## What's New?
This should help with transactions not being rolled back, which breaks the API once a request fails.

## Type of change (pick-one)
- [x] Bug fix (_non-breaking change which fixes an issue_)
- [ ] New feature (_non-breaking change which adds functionality_)
- [ ] Breaking change (_fix or feature that would cause existing functionality to not work as expected_)
- [ ] This change requires a documentation update

## How Has This Been Tested?
I've tested this locally, and it seemed to work.  I cut my network connection, asked some questions, then reconnected and was still able to answer questions.

## Checklist (check-all-before-merge)
_formatting help: `- [x]` means "checked' and `- [ ]` means "unchecked"_

- [ ] I documented my code according to the [Google Python Style Guide][1]

- [ ] I ran `./build_docs.sh` and the docs look fine

- [ ] I ran `./type_check.sh` and got no errors

- [ ] I ran `./format.sh` because it automatically cleans my code for me 😄 

- [ ] I ran `./lint.sh` to check for what "format" missed

- [ ] I added my tests to the `/tests` directory

- [x] I ran `./run_tests.sh` and all the tests pass
image

[1]: https://google.github.io/styleguide/pyguide.html

### CODE REVIEW

**Comment by snekiam** [comment]
I'm not sure if we should just have a catch-all `@app.errorhandler(Exception)`, since that would theoretically handle everything, but it could handle things we don't want it to handle.

**Comment by mfekadu** [comment]
## After sending multiple API requests, I saw how #167 did get _fixed_... 

### Here was my simple request
```
curl --location --request POST 'https://nimbus-pr-168.onrender.com/ask' --header 'Content-Type: application/json' --data-raw '{
	"question": "What is Foaad'\''s email?"
}'
```

### the log for `OperationalErrror`
<details>
<p>

```
May 28 07:41:06 PM  10.100.0.113 - - [29/May/2020:02:41:06 +0000] "GET / HTTP/1.1" 200 37 "-" "Render/1.0"
May 28 07:41:09 PM  [2020-05-29 02:41:08,971] ERROR in app: Exception on /ask [POST]
May 28 07:41:09 PM  Traceback (most recent call last):
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1173, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 775, in _init_compiled
    self.cursor = self.create_cursor()
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 1131, in create_cursor
    return self._dbapi_connection.cursor()
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 978, in cursor
    return self.connection.cursor(*args, **kwargs)
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/mysql/connector/connection_cext.py", line 524, in cursor
    raise errors.OperationalError("MySQL Connection not available.")
mysql.connector.errors.OperationalError: MySQL Connection not available.
May 28 07:41:09 PM  
May 28 07:41:09 PM  The above exception was the direct cause of the following exception:
May 28 07:41:09 PM  
May 28 07:41:09 PM  Traceback (most recent call last):
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/render/project/src/flask_api.py", line 137, in handle_question
    response = {"answer": nimbus.answer_question(question)}
  File "/opt/render/project/src/nimbus.py", line 42, in answer_question
    answer = qa.answer(ans_dict)
  File "/opt/render/project/src/QA.py", line 52, in answer
    db_data = self.db_query(extracted_vars, self.db)
  File "/opt/render/project/src/QA.py", line 231, in _chain_db_access
    for key, val in fn(extracted_vars, db).items():
  File "/opt/render/project/src/QA.py", line 96, in _get_property
    prop=prop, entity=ent, identifier=ent_string
  File "/opt/render/project/src/database_wrapper.py", line 583, in get_property_from_entity
    props = self._get_property_from_entity(prop, entity, identifier, tag_column_map)
  File "/opt/render/project/src/database_wrapper.py", line 558, in _get_property_from_entity
    for row in query_obj.all():
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3233, in all
    return list(self)
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3389, in __iter__
    return self._execute_and_instances(context)
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3414, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1176, in _execute_context
    e, util.text_type(statement), parameters, None, None
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1173, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 775, in _init_compiled
    self.cursor = self.create_cursor()
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 1131, in create_cursor
    return self._dbapi_connection.cursor()
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 978, in cursor
    return self.connection.cursor(*args, **kwargs)
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/mysql/connector/connection_cext.py", line 524, in cursor
    raise errors.OperationalError("MySQL Connection not available.")
sqlalchemy.exc.OperationalError: (mysql.connector.errors.OperationalError) MySQL Connection not available.
May 28 07:41:09 PM  [SQL: SELECT `Profs`.first_name AS `Profs_first_name`, `Profs`.last_name AS `Profs_last_name`, `Profs`.phone_number AS `Profs_phone_number`, `Profs`.research_interests AS `Profs_research_interests`, `Profs`.email AS `Profs_email`, `Profs`.office_hours AS `Profs_office_hours`, `Profs`.platform AS `Profs_platform`, `Profs`.latest_quarter AS `Profs_latest_quarter`, `Profs`.office AS `Profs_office`, `Profs`.department AS `Profs_department`, `Profs`.title AS `Profs_title`
May 28 07:41:09 PM  FROM `Profs`]
May 28 07:41:09 PM  [parameters: [immutabledict({})]]
May 28 07:41:09 PM  (Background on this error at: http://sqlalche.me/e/e3q8)
May 28 07:41:09 PM  
May 28 07:41:09 PM  During handling of the above exception, another exception occurred:
May 28 07:41:09 PM  
May 28 07:41:09 PM  Traceback (most recent call last):
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
```

</p>
</details>


### quickly the API corrected itself to work consistently by reinitializing (which is good! 😄 )

<details>
<p>

```
May 28 07:41:09 PM  {'entity': 'Foaad', 'tag': 'PROF', 'normalized entity': 'Foaad', 'input question': "What is Foaad's email?", 'normalized question': "What is [PROF]'s email?", 'question class': 'What is the email of [PROF]?'}
May 28 07:41:09 PM  initialized database session
May 28 07:41:09 PM  initialized NimbusMySQLAlchemy
May 28 07:41:09 PM  10.104.78.4 - - [29/May/2020:02:41:09 +0000] "POST /ask HTTP/1.1" 500 290 "-" "PostmanRuntime/7.25.0"
May 28 07:41:11 PM  10.100.0.113 - - [29/May/2020:02:41:11 +0000] "GET / HTTP/1.1" 200 37 "-" "Render/1.0"
May 28 07:41:16 PM  10.100.0.113 - - [29/May/2020:02:41:16 +0000] "GET / HTTP/1.1" 200 37 "-" "Render/1.0"
May 28 07:41:18 PM  10.100.0.113 - - [29/May/2020:02:41:18 +0000] "GET / HTTP/1.1" 200 37 "-" "Render/1.0"
May 28 07:41:21 PM  10.100.0.113 - - [29/May/2020:02:41:21 +0000] "GET / HTTP/1.1" 200 37 "-" "Render/1.0"
May 28 07:41:22 PM  [2020-05-29 02:41:22 +0000] [104] [INFO] Booting worker with pid: 104
May 28 07:41:26 PM  10.100.0.113 - - [29/May/2020:02:41:26 +0000] "GET / HTTP/1.1" 200 37 "-" "Render/1.0"
May 28 07:41:28 PM  initialized database session
May 28 07:41:28 PM  initialized NimbusMySQLAlchemy
May 28 07:41:28 PM  {'entity': 'Foaad', 'tag': 'PROF', 'normalized entity': 'Foaad', 'input question': "What is Foaad's email?", 'normalized question': "What is [PROF]'s email?", 'question class': 'What is the email of [PROF]?'}
May 28 07:41:28 PM  [(111, ['Sara', 'Ford'], 'ssford@calpoly.edu'), (131, ['Foaad', 'Khosmood'], 'foaad@calpoly.edu')]
May 28 07:41:28 PM  10.104.78.4 - - [29/May/2020:02:41:28 +0000] "POST /ask HTTP/1.1" 200 73 "-" "PostmanRuntime/7.25.0"
May 28 07:41:31 PM  10.100.0.113 - - [29/May/2020:02:41:31 +0000] "GET / HTTP/1.1" 200 37 "-" "Render/1.0"
May 28 07:41:34 PM  {'entity': 'Foaad', 'tag': 'PROF', 'normalized entity': 'Foaad', 'input question': "What is Foaad's email?", 'normalized question': "What is [PROF]'s email?", 'question class': 'What is the email of [PROF]?'}
May 28 07:41:34 PM  [(111, ['Sara', 'Ford'], 'ssford@calpoly.edu'), (131, ['Foaad', 'Khosmood'], 'foaad@calpoly.edu')]
May 28 07:41:34 PM  10.104.78.4 - - [29/May/2020:02:41:34 +0000] "POST /ask HTTP/1.1" 200 73 "-" "PostmanRuntime/7.25.0"
May 28 07:41:36 PM  10.100.0.113 - - [29/May/2020:02:41:36 +0000] "GET / HTTP/1.1" 200 37 "-" "Render/1.0"
```

</p>
</details>

**Comment by mfekadu** [comment]
# A concern about `response time`
> notice how response time jumps from 2-3 seconds, up to 20ish seconds due to reinitializing the database connection


May-28-2020 20-39-56 2020-05-28 20_46_04



**How might users feel about a response time of 20 seconds for a question?**

**Comment by snekiam** [comment]
I think it would not be a positive experience, but it's better than no response I'd say.  We should definitely figure out *why* this is happening at some point I think.

**Comment by mfekadu** [comment]
Definitely better than no response! 

---

Do you believe this issue is more of a 

1. `MySQL` database thing?

2. `SQLAlchemy` thing?

3. `MySQL && SQLAlchemy` thing?

4. a `NimbusMySQLAlchemy` (the database wrapper) thing?
  * can the code you just added `db.session.rollback()` and `db.session.close()` be a part of the database wrapper itself to both **_separate the concerns_** of the `flask_api` and _**prevent reinitializing**_ the large object (I'm assuming its large by the way... fact check me on this)?

---

Which part of the initialization could be the _slowest_:

1. re-connecting to the database

2. deleting && re-creating the giant `NimbusMySQLAlchemy` object?

---

Which combinations (if any) of answers to the above might give us both
* fast **response time**
* and improved **reliability** (zero downtime) ?

**Comment by mfekadu** [comment]
**One more set of questions as a followup to this previous question**

> Do you believe this issue is more of a
>
> 4. a `NimbusMySQLAlchemy` (the database wrapper) thing?
>  * can the code you just added `db.session.rollback()` and `db.session.close()` be a part of the database wrapper itself to both **_separate the concerns_** of the `flask_api` and _**prevent reinitializing**_ the large object (I'm assuming its large by the way... fact check me on this)?

https://github.com/calpoly-csai/api/blob/ab5b994bc1630afbe4bee2900d623bcf4454db99/flask_api.py#L85-L97


**There are `4` key parts to the solution in this PR, which part is the most important / tackles the root issue?**

1. `@app.errorhandler(OperationalError)`
* if this line is most salient, then what if we found a way to prevent the `OperationalError` entirely

2. `db.session.rollback()`
* if this line is most important, then what if we ran `session.rollback()` per question?

3. `db.session.close()`
* if this line is most vital, then what if we ran `session.close()` per question?

4. `init_nimbus_db()`
* what happens here to make it useful?

**Comment by snekiam** [comment]
> **There are `4` key parts to the solution in this PR, which part is the most important / tackles the root issue?**
> 
>     1. `@app.errorhandler(OperationalError)`
> 
> 
>     * if this line is most salient, then what if we found a way to prevent the `OperationalError` entirely
> 
> 
>     1. `db.session.rollback()`
> 
> 
>     * if this line is most important, then what if we ran `session.rollback()` per question?
> 
> 
>     1. `db.session.close()`
> 
> 
>     * if this line is most vital, then what if we ran `session.close()` per question?
> 
> 
>     1. `init_nimbus_db()`
> 
> 
>     * what happens here to make it useful?

I don't think any piece of this code is the most useful - the problem is that the database connection is tainted, and it takes a couple of things to close it properly and fix it.

**Comment by Jason-Ku** [comment]
The fact that we have latency issues due to our singular connection going down screams to me that we ought to implement connection pooling soon, Could be a potential solve for the latency issue when reinitializing the connection (user can just grab a different connection while one of them spins back up)

**Comment by snekiam** [comment]
My opinion is that we should do a simple change that isn't ideal, but works before doing connection pooling, since that is probably a larger change, and until we do I'd rather have the API have some slow responses rather than it breaking.  I do understand the argument for slowing down and doing it right (connection pooling) though - maybe that is the way to go.

**Comment by Jason-Ku** [comment]
yea, I agree that we ought to have the fix for the individual connection reinitialization first!

**Comment by mfekadu** [comment]
Can we find some SQLAlchemy documentation that points to why there is something wrong with the DB connection?

**Comment by snekiam** [comment]
> 
> 
> Can we find some SQLAlchemy documentation that points to why there is something wrong with the DB connection?

I guess this doesn't say *why*, but an operational error (which is what we're catching) originates in the database driver, according to [this](https://docs.sqlalchemy.org/en/13/errors.html#operationalerror).  It also states that this is the most common error for a dropped database connection, which I *think* is supported by some of the logs from when this occurred:
```
Exception during reset or similar
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/network.py", line 249, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "/usr/lib/python3.8/ssl.py", line 1226, in recv
    return self.read(buflen)
  File "/usr/lib/python3.8/ssl.py", line 1101, in read
    return self._sslobj.read(len)
ConnectionResetError: [Errno 104] Connection reset by peer
```

**Comment by mfekadu** [comment]
relevant comment https://github.com/calpoly-csai/api/pull/114#issuecomment-598524434
@Jason-Ku

**Comment by mfekadu** [comment]
We discussed 

* `pre-ping`

* `pool_size`
  * https://docs.sqlalchemy.org/en/13/core/pooling.html#connection-pool-configuration


We tried
* hitting the server very very fast and experienced the gunicorn server crashing @snekiam 
* boosting the CPU size on Render and noticed a faster `response_time`

**Review by mfekadu — APPROVED** [review]
tentative approval. Let's keep an eye on `response_time`


**quick thought**
another way to reduce `response_time` is to reduce the time to initialize the database.

See logs below (notice the time from previous /GET health check on Render until end of initialize).

Recall the 10-20 second response_time (worse case) from [above GIF](https://github.com/calpoly-csai/api/pull/168#issuecomment-635727893).

```
May 31 03:24:35 PM  10.100.0.113 - - [31/May/2020:22:24:35 +0000] "GET / HTTP/1.1" 200 37 "-" "Render/1.0"
May 31 03:24:38 PM  [2020-05-31 22:24:38 +0000] [118] [INFO] Booting worker with pid: 118
May 31 03:24:40 PM  10.100.0.113 - - [31/May/2020:22:24:40 +0000] "GET / HTTP/1.1" 200 37 "-" "Render/1.0"
May 31 03:24:43 PM  initialized database session
May 31 03:24:43 PM  initialized NimbusMySQLAlchemy
May 31 03:24:43 PM  {'entity': 'Foaad', 'tag': 'PROF', 'normalized entity': 'Foaad', 'input question': 'What is Foaad email?', 'normalized question': 'What is [PROF] email?', 'question class': 'What is the email of [PROF]?'}
May 31 03:24:43 PM  [(111, ['Sara', 'Ford'], 'ssford@calpoly.edu'), (131, ['Foaad', 'Khosmood'], 'foaad@calpoly.edu')]
May 31 03:24:43 PM  10.104.120.5 - - [31/May/2020:22:24:43 +0000] "POST /ask HTTP/1.1" 200 73 "-" "PostmanRuntime/7.25.0"
```

**Review by Jason-Ku — APPROVED** [review]
neeeds further investigation but is a good step forward

**Comment by snekiam** [comment]
So looking into OperationalErrors, gunicorn, and threading.  It seems that this issue doesn't occur when NOT using gunicorn, (just running the flask_api), but I find it odd that multithreading from gunicorn could be causing this (based on information [here](https://davidcaron.dev/sqlalchemy-multiple-threads-and-processes/)).

Hitting the local API with a lot (like a lot) of requests didn't show this issue unless on gunicorn.

Things I think this could be (not exhastive)
- Threading issues (unlikely, but possible- that's one of the differences from gunicorn)
- mysql throttling/crashing in some way - maybe accentuated by multiple processes/threads/workers?
- Something to do with selecting during an insert (from the scraper)
- Non-correlation, some different issue we're not thinking of with the mysql server instance

**Comment by snekiam** [comment]
Response times locally (not on render, running on my laptop):
Normal response: ~2-2.5s
Error handled response (reinit'ing the db): ~4-4.5s

**Pull request merged**
